#!/usr/bin/env bash

declare quiet

bground() {
  ("$@" &> /dev/null &)
}

while getopts ':q' x; do
  case "$x" in
    q) quiet=1 ;;
  esac
done
shift $(( OPTIND - 1 ))

if [[ -n $quiet  ]] && pgrep -x Xorg &> /dev/null; then
  bground mpv ~/Downloads/Store_Door_Chime-Mike_Koenig-570742973.mp3
  (( $# > 0 )) && notify-send -u critical "$@"
else
  if [[ -n $TMUX ]]; then
    m='ding'
    (( $# > 0 )) && m="$*"
    tmux display "$m" // FIXME: longer display time
  fi
  tput bel
fi
