#!/usr/bin/env bash

declare passlist
declare password

declare -r esc=$'\033'
declare -r c_red="${esc}[31m"
declare -r c_reset="${esc}[0m"

err() {
  printf "${c_red}%s${c_reset}\n" "$*" >&2
}

die() {
  (( $# > 0 )) && err "$*"
  exit 1
}

has() {
  local verbose
  if [[ $1 == '-v' ]]; then
    verbose=1
    shift
  fi
  for c in "$@"; do c="${c%% *}"
    if ! command -v "$c" &> /dev/null; then
      (( verbose > 0 )) && err "$c not found"
      return 1
    fi
  done
}

has -v fzf kdbxviewer || die

OPTERR=0
while getopts 'i' opt; do
  case "$opt" in
    i) kdbxviewer -i ~/pass.kdbx; exit ;;
  esac
done
shift $(( OPTIND - 1 ))
unset opt OPTARG OPTIND

passlist=$(kdbxviewer -c ~/pass.kdbx) &&
  password=$(fzf --inline-info --cycle --ansi <<< "$passlist")
[[ -n "$password" ]] || exit 1
password="${password/Generated Password for }"
read -r password <<< "${password#* }"
xclip -r <<< "$password"
