#!/usr/bin/env bash

shopt -s nullglob globstar

in_term() {
  [[ -t 0 || -p /dev/stdin ]]
}

select_from () {
  local a c cmd
  cmd='command -v'
  for a; do
    case "$a" in
      -c) cmd="$2"; 2 ;;
      *) [[ $a = -* ]] && break 2 ;;
    esac
    shift
  done
  for c in "$@"; do
    if $cmd "${c%% *}" &> /dev/null; then
      echo "$c"
      return 0
    fi
  done
  return 1
}

declare generate

  for a; do
    case "$a" in
      -g|--generate) generate=1 ;;
      *) [[ $a = -* ]] && break 2 ;;
    esac
    shift
  done

typeit() {
  prefix=${PASSWORD_STORE_DIR-~/.password-store}
  password_files=( "$prefix"/**/*.gpg )
  password_files=( "${password_files[@]#"$prefix"/}" )
  password_files=( "${password_files[@]%.gpg}" )
  if in_term; then
    password=$(printf '%s\n' "${password_files[@]}" | fzf --inline-info --cycle --ansi)
  else
    password=$(printf '%s\n' "${password_files[@]}" | dmenu -fn "$DMENU_FONT" -z)
  fi

  [[ -z $password ]] && exit

  picker=$(select_from 'slop' 'xprop')

  if in_term && [[ -n $picker ]]; then
    $picker &> /dev/null
  fi

  read -r pass < <(pass show "$password")
  printf '%s' "$pass" | xdotool type --clearmodifiers --file -
}

typeit
