#!/usr/bin/env bash

declare -r esc=$'\033'
declare -r c_red="${esc}[31m"
declare -r c_reset="${esc}[0m"

err() {
  printf "${c_red}%s${c_reset}\n" "$*" >&2
}

has() {
  local verbose=false
  if [[ $1 == '-v' ]]; then
    verbose=true
    shift
  fi
  for c in "$@"; do c="${c%% *}"
    if ! command -v "$c" &> /dev/null; then
      [[ "$verbose" == true ]] && err "$c not found"
      return 1
    fi
  done
}

has -v fzf kdbxviewer || die

passlist=$(kdbxviewer -c ~/pass.kdbx)

password=$(fzf --ansi <<< "$passlist")

[[ -n "$password" ]] && xclip <<< "$password"
