#!/usr/bin/env bash

declare -A known_wms
declare -a avail_wms

known_wms=(
  [awesome]='awesome'
  [bspwm]="bspwm -c $HOME/.config/bspwm/bspwmrc"
  [cinnamon]='cinnamon-session'
  [dwm]='dwm'
  [i3]='i3'
  [lxqt]='dbus-launch lxqt-session'
  [openbox]='openbox-session'
  [kde]='startkde'
  [xfce]='startxfce4'
  [xmonad]='xmonad'
  [xterm]='xterm'
)

has() {
  command -v "$1" &> /dev/null
}

pick() {
  local w wm
  for w in "${!known_wms[@]}"; do
    wm="${known_wms[$w]}"
    has "${wm%% *}" && avail_wms+=( "$w" )
  done

  if has fzf; then
    wm=$(printf '%s\n' "${avail_wms[@]}" | fzf -1 --reverse --inline-info --cycle --margin=40%)
  else
    PS3="choose a number between 1 and ${#avail_wms[@]}: "
    select v in "${avail_wms[@]}"; do
      wm="$v"
      break
    done
  fi

  [[ -n $wm ]] || return 1
  echo "${known_wms[$wm]}"
}

pick
