#!/usr/bin/env bash

declare -r esc=$'\033'
declare -r c_red="${esc}[31m"
declare -r c_reset="${esc}[0m"

err() {
  printf "${c_red}%s${c_reset}\n" "$*" >&2
}

die() {
  [[ -n "$1" ]] && err "$1"
  exit 1
}

select_from() {
  local cmd='command -v'
  for a in "$@"; do
    case "$a" in
      -c)
        cmd="$2"
        shift 2
        ;;
    esac
  done
  for c in "$@"; do
    if $cmd "${c%% *}" &> /dev/null; then
      echo "$c"
      return 0
    fi
  done
  return 1
}

in_term() {
  [[ -t 0 || -p /dev/stdin ]]
}

favs=( v gvim vim emacs vi nano )
editor=$(select_from "${favs[@]}") || die "no editor found in ( ${favs[*]} )"
if in_term; then
  exec "$editor" "$@"
else
  (exec x-terminal-emulator -e bash "$editor" $* &)
fi
