#!/usr/bin/env bash

in_term() {
  [[ -t 0 || -p /dev/stdin ]]
}

declare -a cmds

if tmux ls &> /dev/null; then
  cmds=( tmux attach )
else
  if has tmuxinator; then
    cmds=( tmuxinator start main )
  else
    cmds=( tmux )
  fi
fi

xrdb -load ~/.Xresources
if in_term; then
  exec "${cmds[@]}"
else
  exec x-terminal-emulator -e ${cmds[*]}
fi
