#!/usr/bin/env bash

in_term() {
  [[ -t 0 || -p /dev/stdin ]]
}

has() {
  command -v "$1" &> /dev/null
}

declare -a cmds
declare -a sessions
declare session

mapfile -t sessions < <(tmux ls -F '#S')

if (( ${#sessions[@]} > 0 )); then
  IFS='|' session="${sessions[*]}"
  session="${session##*|}"
  cmds=( tmux attach -t "$session" )
else
  if has tmuxp; then
    cmds=( tmuxp load main )
  else
    cmds=( tmux )
  fi
fi

xrdb -load ~/.Xresources
if in_term; then
  exec "${cmds[@]}"
else
  exec x-terminal-emulator -e "${cmds[@]}"
fi
